# typed: false
# frozen_string_literal: true

# Kno measures the marginal value of data assets for LLM agents.
#
# Generated by goreleaser's brews config at release time (see
# https://github.com/knograph/kno/.goreleaser.yaml); this file for 0.0.2 was
# written by hand because the tap repository was created after that release.
# From the next release on, goreleaser updates it automatically.
class Kno < Formula
  desc "Measure which of your data earns its place in an LLM agent"
  homepage "https://github.com/knograph/kno"
  url "https://github.com/knograph/kno/releases/download/v0.0.2/kno_0.0.2_darwin_arm64.tar.gz"
  sha256 "4a7dddce724b415de5c9c58ad875e3fcfc0092d5097efe501ec343915dec7ce8"
  license "Apache-2.0"
  version "0.0.2"

  on_macos do
    on_arm do
      url "https://github.com/knograph/kno/releases/download/v0.0.2/kno_0.0.2_darwin_arm64.tar.gz"
      sha256 "4a7dddce724b415de5c9c58ad875e3fcfc0092d5097efe501ec343915dec7ce8"
    end
    on_intel do
      url "https://github.com/knograph/kno/releases/download/v0.0.2/kno_0.0.2_darwin_amd64.tar.gz"
      sha256 "c6efb31ae0b23693429a14748c6daa9434d50efdd07407db0eee140f1d02862d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/knograph/kno/releases/download/v0.0.2/kno_0.0.2_linux_arm64.tar.gz"
      sha256 "5623496738458522ad73a4437c6b674b2e9304b5068c14e1ef8196bb29bae8e0"
    end
    on_intel do
      url "https://github.com/knograph/kno/releases/download/v0.0.2/kno_0.0.2_linux_amd64.tar.gz"
      sha256 "eace68f456b5c81dfb624085cee4111bba930c7151670680e61c34f898095c37"
    end
  end

  def install
    bin.install "kno"
  end

  test do
    system "#{bin}/kno", "--version"
  end
end
