# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kno < Formula
  desc "Measure which of your data earns its place in an LLM agent"
  homepage "https://github.com/uknoAI/kno"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/uknoAI/kno/releases/download/v0.2.0/kno_0.2.0_darwin_amd64.tar.gz"
      sha256 "53314e351e72a523ee193e8c4663062057b234ec0f922eb970e10bb1fbb13e62"

      def install
        bin.install "kno"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/uknoAI/kno/releases/download/v0.2.0/kno_0.2.0_darwin_arm64.tar.gz"
      sha256 "d2fd30b61e3895da31d514ce63deb6748cce0f5d4fdfc541b72ef977ba607e84"

      def install
        bin.install "kno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/uknoAI/kno/releases/download/v0.2.0/kno_0.2.0_linux_amd64.tar.gz"
      sha256 "f6a054840649d3dcf1bf8a07e4591911b25fa724ed1b870229cf642d92410fc1"
      def install
        bin.install "kno"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/uknoAI/kno/releases/download/v0.2.0/kno_0.2.0_linux_arm64.tar.gz"
      sha256 "4107d1b5f3cbe7b12fb9f1e38d4c0f61860038127f0b29538b51d9df0977b1e5"
      def install
        bin.install "kno"
      end
    end
  end

  test do
    system "#{bin}/kno", "--version"
  end
end
