# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kno < Formula
  desc "Measure which of your data earns its place in an LLM agent"
  homepage "https://github.com/knograph/kno"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Knograph/kno/releases/download/v0.0.3/kno_0.0.3_darwin_amd64.tar.gz"
      sha256 "57b0083a58451623c5e42e27e4ba61c67dc0c28a6b70612995f671ddcfc6c852"

      def install
        bin.install "kno"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Knograph/kno/releases/download/v0.0.3/kno_0.0.3_darwin_arm64.tar.gz"
      sha256 "112950807ab62a3e088b55f7defd15eef59d5d66ee9292c0cf9eff0c8fac5b0c"

      def install
        bin.install "kno"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Knograph/kno/releases/download/v0.0.3/kno_0.0.3_linux_amd64.tar.gz"
      sha256 "c7197661c7e7bd2d007e446437aad31e5d8d382209c3ffe4b6e546aa7f6735d7"
      def install
        bin.install "kno"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Knograph/kno/releases/download/v0.0.3/kno_0.0.3_linux_arm64.tar.gz"
      sha256 "0a2b2007d6499b10625e881ae41e6ff622d4b3ff0debed773ed23048c1f7b251"
      def install
        bin.install "kno"
      end
    end
  end

  test do
    system "#{bin}/kno", "--version"
  end
end
